# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_cardata'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardata',
            name='bat',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
