# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 18:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_cardata_bat'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noise_refresh_ms', models.IntegerField(default=300)),
                ('smoke_refresh_ms', models.IntegerField(default=1200)),
                ('upload_refresh_s', models.IntegerField(default=20)),
                ('co2_refresh_s', models.IntegerField(default=60)),
                ('valid_since', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('valid_to', models.DateTimeField(blank=True)),
                ('added', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
