# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 18:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_sensorconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorconfig',
            name='valid_since',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='sensorconfig',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
    ]
