# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_auto_20170319_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pollution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2', models.IntegerField()),
                ('smoke', models.IntegerField()),
                ('noise', models.IntegerField()),
                ('received', models.DateTimeField()),
            ],
        ),
    ]
