# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_auto_20170320_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollution',
            name='smoke',
            field=models.FloatField(),
        ),
    ]
