# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-05 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_auto_20170405_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollution',
            name='bat',
            field=models.FloatField(),
        ),
    ]
